// <auto-generated />
using System;
using DemoProtocol_Db_RailwayObjectsPropertiesGetterAndUpdater.Logic.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoProtocol_Db_RailwayObjectsPropertiesGetterAndUpdater.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DemoProtocol_Db_RailwayObjectsPropertiesGetterAndUpdater.Interface.RailwayObjects.Dynamic.Wagon", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<double>("Base")
                        .HasColumnType("float");

                    b.Property<double>("CartBase")
                        .HasColumnType("float");

                    b.Property<string>("CartName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Destroyed")
                        .HasColumnType("bit");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WagonModelName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Wagons");
                });

            modelBuilder.Entity("DemoProtocol_Db_RailwayObjectsPropertiesGetterAndUpdater.Interface.RailwayObjects.Static.Rail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("FrontRailId")
                        .HasColumnType("int");

                    b.Property<int?>("FrontSwitchId")
                        .HasColumnType("int");

                    b.Property<int>("FrontVertexId")
                        .HasColumnType("int");

                    b.Property<int?>("LeftRailId")
                        .HasColumnType("int");

                    b.Property<int?>("RearRailId")
                        .HasColumnType("int");

                    b.Property<int?>("RearSwitchId")
                        .HasColumnType("int");

                    b.Property<int>("RearVertexId")
                        .HasColumnType("int");

                    b.Property<int?>("RightRailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rails");
                });

            modelBuilder.Entity("DemoProtocol_Db_RailwayObjectsPropertiesGetterAndUpdater.Interface.RailwayObjects.Static.Retarder", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("RailId")
                        .HasColumnType("int");

                    b.Property<int>("RwNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Retarders");
                });

            modelBuilder.Entity("DemoProtocol_Db_RailwayObjectsPropertiesGetterAndUpdater.Interface.RailwayObjects.Static.Semaphore", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VertexId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Semaphores");
                });

            modelBuilder.Entity("DemoProtocol_Db_RailwayObjectsPropertiesGetterAndUpdater.Interface.RailwayObjects.Static.Switch", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("LeftRailId")
                        .HasColumnType("int");

                    b.Property<int>("RearRailId")
                        .HasColumnType("int");

                    b.Property<int>("RightRailId")
                        .HasColumnType("int");

                    b.Property<int>("RwNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Switches");
                });

            modelBuilder.Entity("DemoProtocol_Db_RailwayObjectsPropertiesGetterAndUpdater.Interface.RailwayObjects.Static.Vertex", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.Property<double>("Z")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Vertices");
                });
#pragma warning restore 612, 618
        }
    }
}
